name: auto-pr
on:
  push:
    branches:
      - "**"
    branches_ignore:
      - main

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: pull-request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          destination_branch: 'main'
          github_token: ${{ secrets.SEMVER_TOKEN }}