name: auto-pr
on:
  workflow_call:

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pull-request
        uses: diillson/auto-pull-request@v1.0.1        
        env:
          GITHUB_TOKEN: ${{ secrets.SEMVER_TOKEN }}
        with:
          destination_branch: 'main'
          github_token: ${{ secrets.SEMVER_TOKEN }}