on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main      
jobs:    
  version:
    uses: ./.github/workflows/semver.yml
    
  security:
    uses: ./.github/workflows/security.yml
        
  test:
    uses: ./.github/workflows/test.yml

  package-and-publish:
    uses: ./.github/workflows/package-and-publish.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    needs:
      - test
      - version
      - security
    #if: startsWith(github.ref, 'refs/tags/')   
    with:
      version: ${{ needs.version.outputs.version }}
#    name: Package and Publish
#    runs-on: ubuntu-latest     
#    permissions:
#      contents: read
#      packages: write
#      attestations: write
#      id-token: write
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#      - name: Set up cosign
#        uses: sigstore/cosign-installer@main
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      - name: Login to GitHub Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      - name: Publish container image
#        uses: docker/build-push-action@v3
#        env:
#          VERSION: ${{ needs.version.outputs.version }}
#          IMAGE_NAME: black-hole
#        with:
#          push: true
#          builder: ${{ steps.buildx.outputs.name }}
#          context: .
#          file: ./Dockerfile
#          platforms: linux/amd64,linux/arm64
#          tags: |
#            ghcr.io/innago-property-management/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
#          labels: |
#            org.opencontainers.image.title=${{ github.event.repository.name }}
#            org.opencontainers.image.description=${{ github.event.repository.description }}
#            org.opencontainers.image.url=${{ github.event.repository.html_url }}
#            org.opencontainers.image.revision=${{ github.sha }}
#            org.opencontainers.image.version=${{ env.VERSION }}
#      - name: sign container image
#        run: |
#          cosign sign \
#            --key env://COSIGN_KEY \
#            --yes \
#            --upload=true \
#            --tlog-upload=true \
#            --recursive=true \
#            ghcr.io/innago-property-management/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
#        shell: bash
#        env:
#          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
#          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
#          VERSION: ${{ needs.version.outputs.version }}
#          IMAGE_NAME: black-hole
