on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main      
jobs:    
  version:
    uses: ./.github/workflows/semver.yml    
  security:
    uses: ./.github/workflows/security.yml        
  test:
    uses: ./.github/workflows/test.yml
  package-and-publish:
    uses: ./.github/workflows/package-and-publish.yml
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    needs:
      - test
      - version
      - security
    with:
      version: ${{ needs.version.outputs.version }}
      cosignPassword: ${{secrets.COSIGN_PASSWORD}}
      imageName: black-hole
      cosignKey: ${{secrets.COSIGN_KEY}}
