on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:  
  auto-pr:
    uses: ./.github/workflows/auto-pr.yml
      
    
  version:
    uses: ./.github/workflows/semver.yml
    
  security:
    name: Security Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno lint
      - run: deno run -A https://deno.land/x/udd/main.ts src/deno.json

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: ['2.x']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Run tests
        run: deno test src/ --allow-read --allow-net --allow-env

  package-and-publish:
    name: Package and Publish
    runs-on: ubuntu-latest
    needs: 
      - test
      - version
      - security
      - auto-pr
#    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up cosign
        uses: sigstore/cosign-installer@main
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Publish container image
        uses: docker/build-push-action@v3
        env:
          VERSION: ${{ needs.version.outputs.version }}
          IMAGE_NAME: black-hole
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/innago-property-management/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ env.VERSION }}
      - name: sign container image
        run: |
          cosign sign --key env://COSIGN_KEY ghcr.io/innago-property-management/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
        shell: bash
        env:
          COSIGN_KEY: ${{secrets.COSIGN_KEY}}
          COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
          VERSION: ${{ needs.version.outputs.version }}
          IMAGE_NAME: black-hole
