name: security.yml
on:
  workflow_call:

jobs:
  security:
    name: Security Checks
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno lint
      - run: deno run -A https://deno.land/x/udd/main.ts src/deno.json
  
  sast:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: semgrep-action
        uses: semgrep/semgrep-action@v1

  secrets:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: ghcr.io/gitleaks/gitleaks:latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
      - name: GitLeaks
        run: |
          git config --global --add safe.directory /__w/black-hole/black-hole
          gitleaks detect --verbose